name=Dhananjay
username=student
browserName:Chrome
testLogin=https://practicetestautomation.com/practice-test-login/
SwagUrl=https://www.saucedemo.com/
headlessFlag=false
demoQAUrl=https://demoqa.com/